name: workflow

on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: action/checkout
        - uses: actions/setup-node
        - run: make setup
        - run: make start
        - run: make test
        - run: make lint