name: workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
        - uses: action/checkout@v4
        - uses: actions/setup-node@v4
        - run: make setup
        - run: make test
        - run: make lint